server:
  port: 8080
  servlet:
    context-path: /demoo

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/demo"
    username: username
    password: password #nh? MYSQL_PASSWORD, kp pass root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#nh? c?p quy?n cho db demo trong dbeaver; k s? l?i
#?a h?t l?i sao v?n k ch?y ?c postman ta? 400 Bad Request
#oh do sai cú pháp postman